### ISSUE TITLE
UMOG update and curious

### ISSUE THREAD

**Issue by enzyme69** [hsab/GrowthNodes#8]
Hi it's me again, it is 2018 and I am watching this UMOG, so far still kind of confused on how this can be used :) If there is a YouTube video or blog to watch the development and test the add-on, I am here.

Where would be the best to start?

**Comment by enzyme69** [comment]
I remember testing this on Windows and was working, now on Mac, the add-on does not seem to install.

**Comment by enzyme69** [comment]
Error message:
This is just the source code of UMOG, not a compiled or dynamic build.
Please download a build for your operating system instead or run setup.py with --pyximport command.
If you download a build from releases, don't forget to remove this copy first.

**Comment by enzyme69** [comment]
I found the WIKI page:
https://github.com/hsab/UMOG/wiki/Getting-Started-Using-this-Plugin

But still having issue with installation on MacBookPro...

**Comment by hsab** [comment]
Hi Jimmy. Glad you posted this since it made me clean up the repo. Please refer to the readme in the master branch. I've cleaned everything up, removed all the features that required compilation, and have uploaded a youtube video showing how to use the plugin. 

ps. I've been following you and watching your videos for a few years now. So it is quite exciting to see you use the plugin ;)

**Comment by enzyme69** [comment]
@hsab Thanks for this update! I can confirm installation is working now I can see Growth Nodes~ Thanks for the YouTube follow much appreciated, I am basic level, but happy to learn. 

Exploring Growth Nodes now.
