### ISSUE TITLE
Mesh 3D Texture node seems missing

### ISSUE THREAD

**Issue by enzyme69** [hsab/GrowthNodes#9]
I am starting fresh with basic tutorials, but found out some missing nodes. I could not find **Mesh 3D Texture** to generate voxel.

Do you also provide example Blend to start with?

**Comment by hsab** [comment]
Mesh 3D Texture has been removed from the master branch since its pretty hacky. It is available from the experimental branch but is only compiled for windows and unfortunately I don't have access to osx. Also if you are planning to use the master branch which is identified by GrowthNodes instead of UMOG, make sure you fully remove all traces of the previous versions of the addon from the blender preferences folder.
